### ISSUE TITLE
Issue running locally due to documentation issues

### ISSUE THREAD

**Issue by sirajyasin** [tigera/operator#1010]
Issue running locally due to documentation issues

## Expected Behavior

User should be able to successfully deploy calioc via tigera operator following the steps in the README for "Running it locally".

## Current Behavior
Executing the steps mentioned in the README leads to error due to incorrect path
Issues:
	KUBECONFIG=./kubeconfig.yaml go run ./cmd/manager   => incorrect path
	kubectl create -f ./deploy/crds/operator_v1_installation_cr.yaml	=> incorrect path

## Possible Solution

Fix the documentation with correct path and validate the deployment locally

## Steps to Reproduce (for bugs)

Follow the steps mentioned under "Running it Locally"

## Your Environment

* Operating System and version: Ubuntu 18.04.4 LTS

**Comment by tmjd** [comment]
Fixed by #1011

**Comment by tmjd** [comment]
Thank you for reporting this issue.
