### ISSUE TITLE
Multi-architecture Container Image

### ISSUE THREAD

**Issue by cablespaghetti** [tigera/operator#1241]
The container image only supports the amd64 architecture. I am unable to run it on my Raspberry Pi or AWS Graviton instances.

## Expected Behavior

Ideally it would be great to have a multi-architecture "manifest list" image which allows seamless running on multiple CPU architectures (including arm64): https://docs.docker.com/registry/spec/manifest-v2-2/

## Possible Solution

It looks like binaries for multiple architectures are getting built but only a single image. It might be as easy as using Docker Buildx.

**Comment by caseydavenport** [comment]
This should be done now, per @frozenprocess
