### ISSUE TITLE
Support for arm64 architecture

### ISSUE THREAD

**Issue by cguertin14** [tigera/operator#1246]
## Expected Behavior

Tigera-operator behaving normally and running on arm64 clusters as intended.

## Current Behavior

Cannot use tigera-operator on arm64 cluster because of incompatibility with arm64.

## Possible Solution

The solution would be to deploy a tigera-operator arm64 capable Docker image to the https://quay.io/repository/tigera/operator registry.

## Steps to Reproduce (for bugs)

1. Download Tigera Operator's YAML configuration: https://docs.projectcalico.org/manifests/tigera-operator.yaml
2. Apply the manifests on an arm64 server/computer
3. Notice the operator not working because of incompatibility.

## Context

I recently started a Raspberry Pi cluster at home to play with k3s and bare-metal Kubernetes. For my CNI, I chose Calico because I heard great things about it, and then tigera-operator failed to run on my cluster. But, Calico still works and i'm not sure if i need tigera operator at all, but the guide I followed (https://docs.projectcalico.org/getting-started/kubernetes/k3s/quickstart) featured it.

## Your Environment

* Operating System and version: Ubuntu Server 20.04, running on 4 different Raspberry Pi 4b
* Link to your project (optional): https://github.com/cguertin14/infra

**Comment by tmjd** [comment]
Thank you for your interest in Calico and the operator. It would be great if the operator could install other architectures. If you are interested in submitting changes to be able to build an arm64 version I would be happy to review.

For your purposes I think you will be fine using the "Manifest" tab under "Install Calico".

**Comment by cguertin14** [comment]
> Thank you for your interest in Calico and the operator. It would be great if the operator could install other architectures. If you are interested in submitting changes to be able to build an arm64 version I would be happy to review.
> 
> 
> 
> For your purposes I think you will be fine using the "Manifest" tab under "Install Calico".

Sweet! I'll look into it and submit a PR probably this week then 😀

**Comment by jsievenpiper** [comment]
@tmjd I took a very crude stab at providing support -- would love your input when you get the time!

**Comment by HaveFun83** [comment]
Looks like you already have done something with arm64 images according to your makefile?
https://github.com/tigera/operator/blob/a3756a531ee51666cf7a76934f7ee049d8734868/Makefile#L33

**Comment by frozenprocess** [comment]
I believe https://github.com/tigera/operator/pull/1464 and https://github.com/tigera/operator/pull/1469 address this issue.

An early operator image can be find here for testing and hopefully endup in the next release.
```
docker pull quay.io/tigera/operator@sha256:c6d90c996ec3158a7c18d1530e82c3af7dd3264969eff0dbdeffa010ad8fbee0
```

**Comment by jonstevecg** [comment]
Just to provide some supportive feedback...
I updated the latest manifest locally to use that image and it appeared to work well, successfully (so far) upgrading my manifest driven install to the operator install (including moving namespaces).  :)

**Comment by frozenprocess** [comment]
@jonstevecg thanks for the feedback, I was faced with another issue. Seems like `quay.io` manifests are not multiarch atm. 

 btw that API-server problem you mentioned should be fixed with the following PR
Fix: https://github.com/projectcalico/apiserver/pull/63

**Comment by frozenprocess** [comment]
@caseydavenport I think it is safe to close this Ticket.
 #1464 and #1469 extended image creation to support arm64.
#1586 and #1596 PRs added multiarch manifests to `quay.io`.

Users should be able to install `tigera-oprator` in an arm64 environment by using the `nightly` manifest.
```
kubectl apply -f https://docs.projectcalico.org/master/manifests/tigera-operator.yaml
```
