### ISSUE TITLE
Provide a way to disable typha

### ISSUE THREAD

**Issue by jmcshane** [tigera/operator#1282]
As discussed in the Calico documentation, typha is only recommended in large installations: https://github.com/projectcalico/typha#when-should-i-use-typha. My use case has much smaller installations with far less than 50 nodes.

## Expected Behavior

Have a way to disable to typha component in the InstallationSpec.

## Possible Solution

Add an API field that allows enable/disable for each component.

## Context

I am attempting to install calico with typha disabled using the operator.

**Comment by kitos9112** [comment]
I second this - Hitting a very particular issue with Typha as well. I'm running a very lightweight K3s cluster with 5 nodes and don't even see a proper way of configuring some of the Typha deployment. attributes.

There's no easy way to add further environment variables as per Calico reference suggests either.

https://docs.projectcalico.org/reference/typha/configuration
