### ISSUE TITLE
Typha causing APIServer crashes on larger Openshift clusters

### ISSUE THREAD

**Issue by relyt0925** [tigera/operator#1425]
On larger Openshift clusters: restarts of the typha operator cause really large memory spikes that result in the APIServer getting out of memory events and effects downstream components. In my cluster I currently have
12374 pods
225 nodes 
3314 services
```
kubectl get pods --all-namespaces -o wide --no-headers  | wc -l
   13274
   
   kubectl get nodes --no-headers | wc -l
     225

kubectl get services --all-namespaces --no-headers | wc -l
    3314
```

Note we have a total of 3 typha pods in the cluster
```
kubectl get pods -n calico-system -l k8s-app=calico-typha
NAME                           READY   STATUS    RESTARTS   AGE
calico-typha-b66bc54df-44zk7   1/1     Running   0          28m
calico-typha-b66bc54df-shh4f   1/1     Running   0          28m
calico-typha-b66bc54df-vl7jp   1/1     Running   0          28m
```

Posting the associated graphs that show the behavior when restarting typha (I can replicate by simply doing `kubectl delete pods -n calico-system -l k8s-app=calico-typha`) and waiting some time
![Screen Shot 2021-08-03 at 3 43 24 PM](https://user-images.githubusercontent.com/7716924/128083524-c65660b2-c5bd-427e-98db-8558ac1f7852.png)

At the time of the restart the kube-apiserver memory doubles after the restart of the pods (goes up by 20+Gigs). 

The maximum size of the backing database if 4GB. It seems odd that on startup of typha it would result in over 20+GB of utilization when it's meant to be a single "pool" of connecting to the datastore for all the calico-node pods.

## Expected Behavior

Memory usage of the openshift apiserver on a restart of typha should not double. Typha should be able to download the data it needs in a controlled fashion that doesn't cause the APIServer to drastically change from a memory perspective. 

## Current Behavior
At startup of typha pods memory usage drastically increases for the kube-apiserver hosting the cluster (doubles). 

## Possible Solution
Potentially try and rate limit data download for larger clusters? Maybe look at watch optimizations? 

## Steps to Reproduce (for bugs)
1) Get large cluster. The scaling characteristics I put above are within Kubernetes maximums  and can be utilized for reference
2) Restart typha pods 
3) Watch memory of kube-apiserver while the calico-typha pods are starting up (takes about 10 minutes in my monitoring for results to be shown.)

## Context

This issue affects the availability of the kube-apiserver. It can lead to slower processing of other workloads, drastically slower kubectl request processing (to the point where the requests time out), and failure of other control plane components like scheduling of pods, failover of pods, etc. This is due to the fact that calico-typha is consuming all the resources from the kube-apiserver

## Your Environment

* Operating System and version:
* Link to your project (optional):

Cluster: Openshift 4.7.19 (4.7.19_1526_openshift IBM Cloud Openshift cluster)
Details about the scale of the cluster are listed at the top of the issue

**Comment by tmjd** [comment]
I would suggest posting this to github.com/projectcalico/calico as what you are reporting is not something that is special to the operator. If you think it is particularly operator related could you please explain why you believe so.
You should also include the version you are using in your report.

How bad is the utilization if you restart only one typha pod? We wouldn't ever expect someone to restart all the typha pods simultaneously and would suggest not doing that for high availability purposes.

> It seems odd that on startup of typha it would result in over 20+GB of utilization when it's meant to be a single "pool" of connecting to the datastore for all the calico-node pods.
Just imagine if you didn't have typha to fan out the information to all the nodes.

How many apiserver instances are your running? Maybe you need to scale the number of master nodes up.

**Comment by relyt0925** [comment]
Could also be related to this:
https://github.com/projectcalico/typha/issues/492

**Comment by relyt0925** [comment]
I’ll move to typha repo

**Comment by relyt0925** [comment]
I’ll also gather the data on restarting one but I don’t think the startup process should be causing this large of a spike under any circumstances. Or if it is would be interested in what the expected load characteristics are

**Comment by tmjd** [comment]
I'm closing this issue since https://github.com/projectcalico/typha/issues/637 has been created.
