### ISSUE TITLE
The operator namespace is hardcoded

### ISSUE THREAD

**Issue by stevehipwell** [tigera/operator#1427]
## Expected Behavior

The operator should be able to be installed into any namespace.

## Current Behavior

When installing the operator into the _kube-system_ namespace the operator errors because it can't find the _tigera-operator_ namespace.

> {"level":"error","ts":1628066134.605089,"logger":"controller-runtime.manager.controller.tigera-installation-controller","msg":"Reconciler error","name":"default","namespace":"","error":"namespaces \"tigera-operator\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:267\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99"}

## Possible Solution

Remove the hardcoded namespace.

## Steps to Reproduce (for bugs)

Change the namespace in the deployment manifests.

## Context

I'd like more control over how the operator runs.

## Your Environment

AWS EKS v1.21, v1.20, v1.19 & v1.18

**Comment by tmjd** [comment]
What is your use case for wanting to move the operator to a different namespace?

If you are moving the operator to a different namespace you need to set `OPERATOR_NAMESPACE` on the deployment. This is not recommended as we do not test running in a different namespace but it is expected to work.

We've chosen to use multiple namespaces as it is best practice to deploy components in their own namespaces and we've done that with the operator and the components it deploys. The calico-system namespace is where the Calico components will be deployed and if using the Calico APIserver it will have its own namespace. The namespaces the operator deploys cannot be changed. And it is not expected that we would allow configuration of those namespaces without a very compelling use case. I'm mentioning this in case you are considering a follow on request about those namespaces.

**Comment by stevehipwell** [comment]
Thanks for clarifying @tmjd. Operators running in their own namespaces might be documented as a best practice but in reality this isn't necessarily the case when you consider cognitive load, RBAC  concerns and namespace resource allocation. The _prometheus-operator_, the most used operator AFIK, idiomatically runs in the `monitoring` namespace alongside the resources it manages.

The main reason for asking this is because I've just written my own Helm chart for using the Tigera operator and the Helm idiom is to install into the namespace given to Helm so I'd like to support that. It looks like `OPERATOR_NAMESPACE` will solve this for me.

RE output namespaces, for something like Calico and since K8s v1.17 this makes sense (see https://github.com/tigera/operator/issues/1428 for why pre K8s v1.17 I'd have a different opinion), although I would like to see custom labels and annotations as mentioned in https://github.com/tigera/operator/issues/1385.

**Comment by tmjd** [comment]
I'm not super familiar with helm but part of the reason I expect that helm typically uses the namespace given to helm because the majority of helm charts can have multiple deployments in a cluster. Calico is not like that since there is only expected to be one Calico deployment in a cluster. So I'd be cautious about that, but maybe this concern is not related.

Also in case you didn't know, Calico is available in a helm chart https://docs.projectcalico.org/getting-started/kubernetes/helm.

**Comment by tmjd** [comment]
I think the Calico team would be interested to hear your feedback on the helm chart though I think the correct audience would be on github.com/projectcalico/calico rather than here on the operator repo. I'd suggest creating an issue outlining the changes you think that should be made and that you'd be interested in submitting. We'd probably be sensitive to changes that would break compatibility when upgrading from the current chart.

**Comment by stevehipwell** [comment]
@tmjd out of interest how come the Helm chart is in the Calico repo and not in this repo?

**Comment by lwr20** [comment]
> out of interest how come the Helm chart is in the Calico repo and not in this repo?

The helm chart is built out of the manifests in the projectcalico/calico repo, and the build machinery for the helm chart is in the projectcalico/calico Makefile.
