### ISSUE TITLE
Typha pod created by the operator is getting evicted frequently 

### ISSUE THREAD

**Issue by ritesh16300** [tigera/operator#1429]
Typha pod is getting evicted frequently. In a day there are around 390 eviction. I have 150 GB of root ebs volume in the node where typha is running 

This happening on version v3.19.1

![image](https://user-images.githubusercontent.com/16636420/128173402-47ec8ce8-3d46-4d46-a200-8297038439a1.png)
![image](https://user-images.githubusercontent.com/16636420/128173525-9a326157-049f-4973-abe2-2e1a037079d6.png)
![image](https://user-images.githubusercontent.com/16636420/128173582-4bf9f4d0-7c73-4bc6-bbe4-d9fb9a6ed4e2.png)

**Comment by tmjd** [comment]
The Message shows that it was evicted due to disk pressure on the node. I suggest you ensure your nodes have sufficient disk pressure to ensure they do not evict pods unexpectedly.

**Comment by stevehipwell** [comment]
This is potentially related to https://github.com/tigera/operator/issues/1428 as the typha pods don't have `system-cluster-critical` priority so will be more likely to be evicted by the scheduler than if they did.

**Comment by caseydavenport** [comment]
We've updated typha to have system-cluster-critical set. Otherwise, make sure you have enough disk! Closing this one for now.
