### ISSUE TITLE
 Tigera Operator attempts to schedule on Fargate nodes

### ISSUE THREAD

**Issue by jayanthvn** [tigera/operator#1438]
## Expected Behavior

This is an improvement, need to add nodeSelector for calico-node DS to "not" schedule on Fargate nodes. Similar to https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/master/aws-k8s-cni-cn.yaml#L100

## Current Behavior

Please see this - https://github.com/aws/amazon-vpc-cni-k8s/issues/1429

## Possible Solution

https://github.com/aws/amazon-vpc-cni-k8s/issues/1429#issuecomment-863256146

## Steps to Reproduce (for bugs)

1. Steps to repro are here - https://github.com/aws/amazon-vpc-cni-k8s/issues/1429

## Your Environment

* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Agreed, should be straightforward to add a node selector expression for EKS clusters to avoid fargate nodes.

**Comment by tmjd** [comment]
This would probably be something like https://github.com/tigera/operator/blob/7b6c0dc33f0f08655637ae8b01232a255e13d4c9/pkg/render/node.go#L658 but changed to avoid fargate nodes

**Comment by caseydavenport** [comment]
This has been fixed by https://github.com/tigera/operator/pull/1725
