### ISSUE TITLE
Typha autoscaler should exclude tainted nodes in node count

### ISSUE THREAD

**Issue by tscn** [tigera/operator#1441]
## Expected Behavior

We are managing a pipeline to provide on-demand deployments of preconfigured EKS clusters. The created EKS clusters are initially deployed with a small footprint which in a two-AZ deployment would only be two nodes (one managed node group per AZ with one node each). From there users can scale up or use cluster-autoscaling according to their needs. To follow the recommended deployment approach for Calico (also on AWS: https://docs.aws.amazon.com/eks/latest/userguide/calico.html), we switched from the helm-based deployment to the operator-based installation method. 
When a new EKS version is released, we want to upgrade these two-node cluster to a new version which includes an upgrade of the control plane and the managed worker nodes. The expectation is that this also works with tigera-operator installed in the cluster.

## Current Behavior

When we upgrade the managed worker nodes of a two-node EKS cluster (e.g. from version 1.20 to 1.21) the worker node upgrade fails with a PodEvictionFailure in terraform after almost 30 minutes.

```
Error: error waiting for EKS Node Group (...) version update (...): EKS Node Group (...) update (...) status (Failed) not successful: Errors:
Error 1: Code: PodEvictionFailure / Message: Reached max retries while trying to evict pods from nodes in node group xyz
``` 

The assumed cause here is that for a two-node cluster the typha-autoscaler is "incompatible" with the EKS managed worker node upgrade behavior which is described here: https://docs.aws.amazon.com/eks/latest/userguide/managed-node-update-behavior.html

It says:

> ...
> - Checks the nodes in the node group for the eks.amazonaws.com/nodegroup-image label, and applies a eks.amazonaws.com/nodegroup=unschedulable:NoSchedule taint on all of the nodes in the node group that aren't labeled with the latest AMI ID. This prevents nodes that have already been updated from a previous failed update from being tainted.
> - Randomly selects up to max nodes to upgrade in parallel.
> - Cordons the node after all of the pods are evicted. This is done so that the service controller doesn't send any new requests to this node and removes this node from its list of healthy, active nodes.
> - ...

Only when we do a manual `kubectl cordon` of nodes with a `eks.amazonaws.com/nodegroup=unschedulable:NoSchedule` taint while the worker node upgrade is performed, the upgrade is successful.

## Possible Solution

If the typha-autoscaler (https://github.com/tigera/operator/blob/master/pkg/controller/installation/typha_autoscaler.go#L243) would exclude tainted nodes from the node count for required typha instances like it excludes unschedulable nodes, the upgrade could work without manual intervention.

## Steps to Reproduce (for bugs)

1. Create an EKS cluster with two managed nodes.
2. Install tigera-operator on EKS cluster.
3. Perform a version upgrade for managed nodes.

## Context

We also noticed a similar issue with cluster-autoscaler just as described in https://github.com/tigera/operator/issues/1295. With excluding tainted nodes from the calculation in typha-autoscaler this should also solve the issue with cluster-autoscaler because the documentation of CA says:

> What happens when a non-empty node is terminated? As mentioned above, all pods should be migrated elsewhere. Cluster Autoscaler does this by evicting them and tainting the node, so they aren't scheduled there again.

## Your Environment

* CSP: AWS
* Service: EKS
* K8s version: 1.20 / 1.21

**Comment by amitkatyal** [comment]
@tmjd I tested with the latest calico operator (v1.21.0) which is under review - **https://github.com/aws/amazon-vpc-cni-k8s/pull/1578** and observed that upgrade to new k8s release, node deletion & cluster auto-scaling use-cases are working fine. Just wanted to double confirm if the issue has been fixed in the latest release?

I tested the k8s upgrade (two-node cluster) from 1.19 to 1.20 to 1.21 and the upgrade worked fine both times. Also tested that once the "scheduling disabled" taint was added to the node, the calico-typha POD was evicted.

Same observation with the cluster auto-scaling &  manually adding/deleting the nodes from the Managed node group. Please note that I had tested with a minimum two number of nodes and two typha were always available.

If the above observation is expected as per the changes, then can wait for the latest changes to get merged. Kindly confirm.

**Comment by tmjd** [comment]
We didn't explicitly fix this issue (AFAIK) but this newer version does include ignoring Unschedulable nodes for typha, so perhaps that has addressed the issue.

**Comment by amitkatyal** [comment]
Thanks for the confirmation!

**Comment by tmjd** [comment]
Even thought it sounds like this might be resolved on EKS I thought I'd mention this here.
We're expecting to discuss issues around scaling and Typha next week (Sept 8th, 2021) in the Calico community meeting if anyone here wants to join to be part of that discussion feel free to join. You can find the details to join here https://github.com/projectcalico/community

**Comment by tscn** [comment]
@amitkatyal I can confirm your observation that it is working now with the latest version of the operator. I tested both upgrade from EKS 1.20 to 1.21 and also cluster-autoscaler in 1.21. Thank you for testing and sharing!

**Comment by amitkatyal** [comment]
@tscn Thanks for the confirmation!

**Comment by tscn** [comment]
@amitkatyal @tmjd While running continuous tests for release preparation, we came to the conclusion that the issue still occurs sometimes. We are seeing node group updates where the typha pod is continuously evicted and immediately rescheduled on the same node, i.e. the desired replica count is still higher than the number of untainted nodes in the cluster. The upgrade finally fails because of PodEvictionFailure. We have not found any other issues so I assume some kind of race condition between rescheduling the pod and cordoning the node. We are now trying to switch to operator version 1.22.0 which allows the `controlPlaneTolerations` to be applied to typha pods (as suggested in https://github.com/projectcalico/calico/issues/4695). 
I can re-open this issue if it makes sense to look into excluding tainted nodes in the node count for typha, but the solution proposed in https://github.com/tigera/operator/pull/1506/files will also work for us (as long as one single typha instance is sufficient to ensure reliable network policy enforcement also is small clusters).

**Comment by amitkatyal** [comment]
@tscn Thanks for the update!
Could you please explain how adding controlPlaneTolerations will fix the issue?. As we are deploying the calico using the manifest, how to apply the "controlPlaneTolerations"?. Does it require modifying the operator manifest?

Regarding the https://github.com/tigera/operator/pull/1506/files solution, I could see the PR is in the open state.  Is there a plan to merge this PR as this would indeed fix the issue?  

Could you also confirm that updating the existing cluster with the new release will not have any issues right?

**Comment by amitkatyal** [comment]
@tscn Could you please clarify? Thanks!!

**Comment by tscn** [comment]
@amitkatyal I'm just the author of the issue and not a Tigera member or contributor - so questions regarding merging PR's and version compatibility have to be answered by @tmjd or someone else. 

The `controlPlaneTolerations` can be set in the Installation.spec - https://docs.projectcalico.org/reference/installation/api#operator.tigera.io/v1.InstallationSpec. We changed it for NoSchedule to operator Equal and custom key/value. After some test iterations, it seems to work (but error is anyway random). Now we ran into the problem that actually the operator pod itself caused a node upgrade to fail because it also has these generous tolerations and it was again and again rescheduled on the node that was being evicted by the AWS EKS node upgrade procedure. So we have to patch the operator manifest to remove or change the tolerations.

**Comment by amitkatyal** [comment]
@tscn Thanks for the update!

@tmjd Could you please help on how do we modify the controlPlaneTolerations (w/o manual intervention) if we are deploying the calico using the operator manifest recommended by the AWS?

As per my understanding typha pod is created by the tigera-operator, If so, how to control the typha pod toleration (controlPlaneTolerations) from the tigera-operator manifest.

**Comment by tscn** [comment]
@amitkatyal `controlPlaneTolerations` can be applied like this:

```yaml
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  controlPlaneTolerations:
  - effect: NoSchedule
    operator: Equal
    key: your-custom-key
    value: your-custom-value
```

From what I saw, it is not possible to override the tolerations with an empty array, then the all-tolerations are applied again. This means you have to provide a key-value combination you can choose, but that should be different than the one AWS uses.

Update from our testing: it works and if you also override the tolerations for the tigera-operator deployments, node group updates for 2-node clusters (one node group per AZ on 2-AZ deployment) are successful. Tested for upgrade scenario where we switch AMI from 1.20 to 1.21.

The bad news is:, Cluster-Autoscaler still does not work. I am not sure if I did something wrong in my first test or if it is a random issue but with the test on EKS 1.21 with tigera-operator 1.22.0, it does not work. CA reports the same message described here: https://github.com/projectcalico/calico/issues/4695#issuecomment-866952937

**Comment by amitkatyal** [comment]
@tscn Thanks for your inputs! Will try as per your suggestion.

**Comment by L1ghtman2k** [comment]
> @amitkatyal `controlPlaneTolerations` can be applied like this:
> 
> ```yaml
> apiVersion: operator.tigera.io/v1
> kind: Installation
> metadata:
>   name: default
> spec:
>   controlPlaneTolerations:
>   - effect: NoSchedule
>     operator: Equal
>     key: your-custom-key
>     value: your-custom-value
> ```
> 
> From what I saw, it is not possible to override the tolerations with an empty array, then the all-tolerations are applied again. This means you have to provide a key-value combination you can choose, but that should be different than the one AWS uses.
> 
> Update from our testing: it works and if you also override the tolerations for the tigera-operator deployments, node group updates for 2-node clusters (one node group per AZ on 2-AZ deployment) are successful. Tested for upgrade scenario where we switch AMI from 1.20 to 1.21.
> 
> The bad news is:, Cluster-Autoscaler still does not work. I am not sure if I did something wrong in my first test or if it is a random issue but with the test on EKS 1.21 with tigera-operator 1.22.0, it does not work. CA reports the same message described here: [projectcalico/calico#4695 (comment)](https://github.com/projectcalico/calico/issues/4695#issuecomment-866952937)

I am not sure how this actually helps. The problem is that typha is deployed to tainted nodes, but controlPlaneTolerations doesn't affect Typha's tolerations (https://github.com/tigera/operator/issues/1653)

**Comment by L1ghtman2k** [comment]
Note: tigeria versions < v1.22.0 did not have controlPlaneTolerations apply to Typha. (Was fixed here: https://github.com/tigera/operator/commit/ef4c15f4cdfdcf17e358416aaf0f5269c8521bbd)
