### ISSUE TITLE
Provide flexibility of installing calico in an existing namespace as oppose calico-system namespace

### ISSUE THREAD

**Issue by faarshad** [tigera/operator#1478]
The default installation of calico creates a new namespace called calico-system. Some organizations require calico to be installed in an existing namespace. the current Installation CRD does not support this functionality.
## Expected Behavior

The installation CRD should probably have a field for installing calico in an existing namespace
## Current Behavior
calico-system namespace is created by the operator always.

## Context
We do not want to manage another namespace only for calico operations so we cannot deploy the tigera-operator until the Installation spec provides flexibility to install in an existing namespace.

## Your Environment
EKS 1.19

* Operating System and version: bottlerocket-v1.0.8

**Comment by tmjd** [comment]
Without more details on the use case that makes this required I don't think we would move forward with a change like this so I'm closing this issue. If more details are added we can re-open the issue.

**Comment by scbunn** [comment]
> with that being said I'm not sure what the use case would be that a namespace other than calico-system would be needed

We have targeted OPA/Gatekeeper polices and depend on namespaces having particular prefixes.  For our particular use case it would be better to have the ability to install into `kube-system` then `calico-system` which does not match any of our known patterns

In general I think it's best to leave things like namespaces up to the end user to decide.
