### ISSUE TITLE
Operator migration: unsupported variables

### ISSUE THREAD

**Issue by taxilian** [tigera/operator#1503]
## Expected Behavior

As long as nothing too outlandish is being done, the migration should detect options and migrate to use the calico operator

## Current Behavior

While migrating I hit a number of areas where it wouldn't let me go while still doing what seem to be very reasonable things:

- FELIX_IPV6SUPPORT=true is not supported
- IP6=autodetect is not supported
- IP_AUTODETECTION_METHOD=cidr=10.21.32.0/23 is not supported. To fix it, remove the IP_AUTODETECTION_METHOD env var or set it to 'first-found', 'can-reach=*', 'interface=*', or 'skip-
interface=*'

I should be able to get around it, but the last one is a particular issue because not all of my nodes have identical hardware, so autodetecting by interface name isn't a good option.

## Context

It doesn't look like it's possible for me to migrate without losing at least ipv6 support until after the migration; the IP_AUTODETECTION_METHOD issue makes migration iffy at best, since if I make a mistake the networking between my pods could get messed up; I use zerotier on my nodes to allow me to communicate with them from anywhere and sometimes calico tries to use that as the interface.

## Your Environment

Ubuntu 20.04, kubeadm cluster 1.22.0

**Comment by caseydavenport** [comment]
Working on fix for the IP_AUTODETECTION_METHOD issue here: https://github.com/tigera/operator/pull/1502/

**Comment by tmjd** [comment]
I've raised this internally to try to get this prioritized but if anyone in the mean time wants to take a shot at this I would be happy to review.
I believe the kind cluster that can be created with `make cluster-create` is a dual stack cluster so could make a nice test bed for deploying an IPv6 dual stack manifest based cluster and then testing migration to an operator based one.
