### ISSUE TITLE
Missing tag 1.20.4 on quay for operator image

### ISSUE THREAD

**Issue by kubealex** [tigera/operator#1553]
Image 1.20.4 (default in manifests in the quickstart) seems to be missing from quay.io:

podman pull quay.io/tigera/operator:v1.20.4
Trying to pull quay.io/tigera/operator:v1.20.4...
Error: Error initializing source docker://quay.io/tigera/operator:v1.20.4: Error reading manifest v1.20.4 in quay.io/tigera/operator: manifest unknown: manifest unknown

**Comment by mgleung** [comment]
Sorry, the operator image publishing got delayed slightly so it didn't make it when the v3.20.2 release got published. The images should all be published now but if you still see any of these errors, please let us know.
