### ISSUE TITLE
Chart version 3.20.2 and 3.20.1 missing

### ISSUE THREAD

**Issue by LCaparelli** [tigera/operator#1645]
We have a chart that pulls the operator chart as dependency.

```yaml
apiVersion: v2
appVersion: "1.0"
description: A Helm chart for tigera-operator
name: tigera-operator
version: "0.0.1"
dependencies:
  - name: tigera-operator
    version: "v3.20.2"
    repository: https://docs.projectcalico.org/charts
```
It used to work fine, but now when attempting to deploy it we run into:

```
❯ helm3 repo add project-calico https://docs.projectcalico.org/charts
❯ helm3 dependency build
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "localstack-repo" chart repository
...Successfully got an update from the "hashicorp" chart repository
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "strimzi" chart repository
...Successfully got an update from the "project-calico" chart repository
...Successfully got an update from the "gympass" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Save error occurred:  could not find : no matching version
Error: could not find : no matching version
```

Even the [docs](https://docs.projectcalico.org/archive/v3.20/getting-started/kubernetes/helm) mention version 3.20.2 as the latest minor for 3.20:
```
helm show values projectcalico/tigera-operator --version v3.20.2
```
## Expected Behavior

That we have access to all versions on Helm.

## Current Behavior

We only have access up to 3.20.0:
```
❯ helm3 search repo project-calico -l
NAME                          	CHART VERSION	APP VERSION	DESCRIPTION                            
project-calico/tigera-operator	v3.20.0      	v3.20.0    	Installs the Tigera operator for Calico
project-calico/tigera-operator	v3.19.2      	v3.19.2    	Installs the Tigera operator for Calico
project-calico/tigera-operator	v3.19.1      	v3.19.1    	Installs the Tigera operator for Calico
project-calico/tigera-operator	v3.19.0      	v3.19.0    	Installs the Tigera operator for Calico
project-calico/tigera-operator	v3.18.4      	v3.18.4    	Installs the Tigera operator for Calico
project-calico/tigera-operator	v3.18.3      	v3.18.3    	Installs the Tigera operator for Calico
project-calico/tigera-operator	v3.18.2      	v3.18.2    	Installs the Tigera operator for Calico
project-calico/tigera-operator	v3.18.1      	v3.18.1    	Installs the Tigera operator for Calico
project-calico/tigera-operator	v3.18.0      	v3.18.0    	Installs the Tigera operator for Calico
```

## Context

We can't move forward with a new deployment changing configuration in our production environment. For a quick fix we plan on downgrading to 3.20, which is not ideal.

For completeness' sake, here's the output prior to running `helm repo update`, showing the 3.20.2 version:
```
❯ helm search project-calico -l
NAME                          	CHART VERSION	APP VERSION	DESCRIPTION                            
project-calico/tigera-operator	v3.20.2      	v3.20.2    	Installs the Tigera operator for Calico
```

## Your Environment

* Operating System and version: AWS EKS 1.21
* Link to your project (optional):

**Comment by mgleung** [comment]
Hi, based on the commands you've listed here, it seems that there might be a typo in your `helm show values` command. Can I have you try `helm show values project-calico/tigera-operator --version=v3.20.2` and see if that works?

**Comment by LCaparelli** [comment]
Hey @mgleung I copied and pasted that command from the docs, I never really ran it. It was to make a point that the latest version should indeed be 3.20.2, and not 3.20.0.

In any case I figured I'd run search again just in case and all versions seem to be up now:
```
helm3 search repo project-calico -l
NAME                          	CHART VERSION	APP VERSION	DESCRIPTION                            
project-calico/tigera-operator	v3.21.0      	v3.21.0    	Installs the Tigera operator for Calico
project-calico/tigera-operator	v3.20.2      	v3.20.2    	Installs the Tigera operator for Calico
# output omitted
```

So not sure what happened, but seems to be fixed now. :-)

I will say that this is not the first time this happens though, not long ago our pipelines were broken because of the same reason; much like this time the problem solved itself. Might be worth looking into it. Thanks for you time!
