### ISSUE TITLE
tigera installation from digest fails

### ISSUE THREAD

**Issue by jacek-czernik** [tigera/operator#1655]
When installing calico from the private registry by digest as described [here ](https://docs.projectcalico.org/maintenance/image-options/imageset) the tigera installation object claims that it requires calico/windows-upgrade to be present in the imageSet.

## Expected Behavior

windows related image should not be required when installing calico on linux

## Current Behavior

when  calico/windows-upgrade is not provided, the tigera installation degrades 

## workaround
Add to mine imageSet calico/windows-upgrade entry with fake digest
  - image: "calico/windows-upgrade"
    digest: "sha256:27878b4f6665bf84549254d688d3610674e613813cb864f0bf503654cf4fb926"

## Steps to Reproduce (for bugs)

follow the instructions from  https://docs.projectcalico.org/maintenance/image-options/imageset

## Context

I'd like to install calico from a private registry.

## Your Environment

kubernetes 1.21
calico 3.21

**Comment by tmjd** [comment]
Thank you for reporting this. I've asked someone to update the document so it has the complete set necessary.

**Comment by jacek-czernik** [comment]
Not sure if changing the document will help much as the windows image is not searchable with the linux docker client.

**Comment by lmm** [comment]
Thanks for reporting this @jacek-czernik - the image set docs are updated now. https://projectcalico.docs.tigera.io/maintenance/image-options/imageset
