### ISSUE TITLE
Allow resource settings to be specified for API Server

### ISSUE THREAD

**Issue by alzabo** [tigera/operator#1757]
## Expected Behavior
API Server resources may be defined in the `Installation` definition

## Current Behavior
The generated api-server Deployment does not set any resource config for its containers.

Cluster administrators who wish to specify resources must apply patches either manually or via tools such as mutating webhooks.

Other components managed by the tigera-operator such as Node, Typha and KubeControllers support resource configuration set in Installation by cluster administrators.

## Possible Solution
Permit ComponentResources for the API Server to be specified via the existing `spec.componentResources` interface on Installation

## Context

Setting resource configs for pods helps to ensure availability generally, and may be employed by cluster admins to set QoS class for pods.

## Your Environment

* Operating System and version: Kubernetes 1.19; EKS using AWS VPC CNI
* Link to your project (optional):

**Comment by tmjd** [comment]
I agree we need to expose setting resource requests and limits but instead of being on the Installation resource I would expect it to go on the APIServer resource using the same pattern as the Installation resource.
If anyone wants to submit a PR to add this I would be happy to review it.

**Comment by lmm** [comment]
Hey @alzabo 

We've put up an outline of proposed changes to operator component configuration which will include setting resource requirements for components like the API Server. Please take a look. We'd appreciate your input on the proposed changes: https://github.com/tigera/operator/issues/1990

**Comment by lmm** [comment]
With #2063 merged it is now possible to add custom resources to the core Calico component containers.
