### ISSUE TITLE
Couldn't install charts because of existing resources

### ISSUE THREAD

**Issue by whoisxx** [tigera/operator#1780]
I have issue with installing calico with tigera-operator.
First I installed in application's namespace so that I uninstall charts and re-install to tigera-operator namespace, but It fails with errors below.
`
Error: rendered manifests contain a resource that already exists. 
Unable to continue with install: Namespace "tigera-operator" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "calico"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "tigera-operator"
`

## Expected Behavior
- Succefully install calico with no errors
- Or indicate which resources are issue

## Current Behavior

- Succefully install calico with no errors

## Possible Solution

- It could be better if there is guide to delete old resources manually.

## Steps to Reproduce (for bugs)

1. install calico with this command `helm install calico projectcalico/tigera-operator --version v3.21.4` to namespace-1
2. un-install calico with this command `helm uninstall calico` in namespace-1
3. re-install calico `helm install calico projectcalico/tigera-operator --version v3.21.4` to tiger-operator namespace

## Context

I found out there are un-removed CustomResourceDefinition as below
```
bgpconfigurations.crd.projectcalico.org               2022-02-11T06:34:30Z
bgppeers.crd.projectcalico.org                        2022-02-11T06:34:30Z
blockaffinities.crd.projectcalico.org                 2022-02-11T06:34:30Z
caliconodestatuses.crd.projectcalico.org              2022-02-11T06:34:30Z
clusterinformations.crd.projectcalico.org             2022-02-11T06:34:30Z
felixconfigurations.crd.projectcalico.org             2022-02-11T06:34:30Z
globalnetworkpolicies.crd.projectcalico.org           2022-02-11T06:34:30Z
globalnetworksets.crd.projectcalico.org               2022-02-11T06:34:30Z
hostendpoints.crd.projectcalico.org                   2022-02-11T06:34:30Z
ipamblocks.crd.projectcalico.org                      2022-02-11T06:34:30Z
ipamconfigs.crd.projectcalico.org                     2022-02-11T06:34:30Z
ipamhandles.crd.projectcalico.org                     2022-02-11T06:34:30Z
ippools.crd.projectcalico.org                         2022-02-11T06:34:30Z
ipreservations.crd.projectcalico.org                  2022-02-11T06:34:30Z
kubecontrollersconfigurations.crd.projectcalico.org   2022-02-11T06:34:30Z
networkpolicies.crd.projectcalico.org                 2022-02-11T06:34:30Z
networksets.crd.projectcalico.org                     2022-02-11T06:34:30Z
apiservers.operator.tigera.io                         2022-02-11T06:34:30Z
imagesets.operator.tigera.io                          2022-02-11T06:34:30Z
installations.operator.tigera.io                      2022-02-11T06:34:31Z
tigerastatuses.operator.tigera.io                     2022-02-11T06:34:31Z 
```

and delete thems or  label thems manually like 
```
labels
- app.kubernetes.io/managed-by=Helm
annotations
- meta.helm.sh/release-name=calico
- meta.helm.sh/release-namespace=tigera-operator
```

but It still generate the error above

## Your Environment

* Operating System and version: EKS 1.21
* Link to your project (optional):

**Comment by tmjd** [comment]
I think the error you're reporting is due to the helm chart you're using doesn't support installing to the tigera-operator namespace since that namespace is hard coded in the chart. See https://github.com/projectcalico/calico/issues/4812.

I think the CRDs not being removed is a separate issue, but I think that might just be the way CRDs are handled by helm.

**Comment by tmjd** [comment]
If you think there is something here not covered by https://github.com/projectcalico/calico/issues/4812 feel free to respond here and I can re-open this. I think more appropriately would be to create an issue in https://github.com/projectcalico/calico, since that is the source of the chart I believe you are referring to.
