### ISSUE TITLE
Ability to update default Felix and Typha Healthports where 9098, 9099 and Promentheus (9091) are already in use

### ISSUE THREAD

**Issue by howels** [tigera/operator#1789]
## Expected Behaviour

Ability to customise healthcheck ports and others (TCP 9091, 9098, 9099)

## Current Behaviour

Cannot customise healthcheck ports using Operator.
 
## Possible Solution

Expose port configuration for ports such as 9091, 9098 and 9099 where it is possible that other application on the host already use these ports.

**Comment by howels** [comment]
> Thank you for the issue. There is this issue [projectcalico/calico#5697](https://github.com/projectcalico/calico/issues/5697) that is covering Felix and Typha Healthports.
> 
> For prometheus we have a NodeMetricsPort and TyphaMetricsPort in the Installation Spec. Do those fit your needs for prometheus?

That issue should cover this ask - I am already in conversation with Manuel on that other Calico issue. But we do want to make sure that these are exposed in the Operator also and not just in Calico CRDs

**Comment by tmjd** [comment]
>But we do want to make sure that these are exposed in the Operator also and not just in Calico CRDs

We do not expose all configuration through the Operator CRDs, ideally we aren't duplicating Calico CRD configuration but I know we do duplicate some. I doubt we will be exposing the FelixHealthPort through the Operator.
It should be possible to install the CRDs (both operator and Calico) and pre-create a FelixConfiguration resource with the desired health port.

**Comment by caseydavenport** [comment]
Will be available in the next release
