### ISSUE TITLE
Operator logs '"Failed to check for failing pods","reason":null' after Upgrade to 1.27.0

### ISSUE THREAD

**Issue by wiswesser** [tigera/operator#1950]
## Expected Behavior

Either no error (If there is none), or a description, so I can figure out, what I am doing wrong.

## Current Behavior

When upgrading to 1.27.0 the operator continously logs:
`{"level":"info","ts":1652257298.9532304,"logger":"status_manager","msg":"Failed to check for failing pods","reason":null,"deployment":"calico-apiserver/calico-apiserver"}
{"level":"info","ts":1652257303.9466262,"logger":"status_manager","msg":"Failed to check for failing pods","reason":null,"deployment":"calico-apiserver/calico-apiserver"}
{"level":"info","ts":1652257303.9468994,"logger":"status_manager","msg":"Failed to check for failing pods","reason":null,"daemonset":"calico-system/calico-node"}`

Downgrading to 1.26.1 removes the problem. So it seems to be related to the new version.

## Possible Solution

I checked the code, and the error is thrown in the syncState Function in controller/status/status.go. But the line is surrounded by a if (err != nil), so I have no idea, why this would happen.

## Context

I am trying to deploy version 1.27.0

## Your Environment

A simple 3 Node Development bare metal Kubernetes Cluster, running on Ubuntu Server 20.04

**Comment by wiswesser** [comment]
Just checked again, and it looks like there is a bug in the previously mentioned status.go file:
`if f, err := m.podsFailing(ds.Spec.Selector, ds.Namespace); err != nil {
    if f != "" {
        failing = append(failing, f)
    }
} else {
	log.WithValues("reason", err, "daemonset", dsnn).Info("Failed to check for failing pods")
	continue
}`
This should be `if err == nil`. As it stands now, the value f is checked, if err is not nil (So an error occured). And the message, that an error occured is printed, if err is nil (So no error occured).

**Comment by tmjd** [comment]
Thank you for the reports and finding the problem. I've put up #1951 to fix that, I'll push to get it picked into the v1.27 branch and get a release created.
