### ISSUE TITLE
Operator bails out on unknown kubernetesProvider

### ISSUE THREAD

**Issue by bootc** [tigera/operator#2066]
I'm using [RKE2](https://docs.rke2.io/), but am installing and managing Calico myself rather than using the version bundled with RKE2 for various reasons.

This worked up to v1.27.4 but has been broken since v1.27.5. I suspect #2005 (cherry-pick of #1983).

## Expected Behavior

Updating the operator should update and (re-)configure Calico.

## Current Behavior

`
{"level":"error","ts":1657097343.7042975,"logger":"controller_installation","msg":"Failed to write defaults","Request.Namespace":"","Request.Name":"default","error":"Installation.operator.tigera.io \"default\" is invalid: spec.kubernetesProvider: Unsupported value: \"RKE2\": supported values: \"\", \"EKS\", \"GKE\", \"AKS\", \"OpenShift\", \"DockerEnterprise\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:214"}
`

## Possible Solution

It looks like `RKE2` was only partially added to to a list of supported Kubernetes providers?

## Steps to Reproduce (for bugs)

Install Tigera Operator 1.27.5 or higher on an RKE2 cluster.

## Context

n/a

## Your Environment

* Operating System and version: Debian bookworm/testing

**Comment by caseydavenport** [comment]
This should do it: https://github.com/projectcalico/calico/pull/6325
