### ISSUE TITLE
Configure csi-node-driver in Installation custom resource

### ISSUE THREAD

**Issue by mottodora** [tigera/operator#2166]
Hello.
I would like to modify the toleration of csi-node-driver.
https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.Installation
However it seems there aren't any fields in Installation to configure csi-node-driver. Is there other way to configure it?

**Comment by tmjd** [comment]
@lmm @Josh-Tigera I think you both were probably working on CSI and the new DaemonSet/Deployment configuration features at the same time and we didn't realize that we should have been adding the configuration for the new CSI daemonset.

@mottodora I think the answer right now is we don't have a way to configure that.

**Comment by radekg** [comment]
Oh, so that implies it's also impossible to configure labels for the `csi-node-driver` `DaemonSet`?

**Comment by Josh-Tigera** [comment]
@radekg you might be interested in this PR another user put up: https://github.com/tigera/operator/pull/2331

**Comment by radekg** [comment]
@Josh-Tigera awesome, thank you. In other words, you‘d accept a PR.

**Comment by tmjd** [comment]
I believe this is available in Calico v3.25.
