### ISSUE TITLE
CVE found in tigera/operator v1.27.12

### ISSUE THREAD

**Issue by codechris1** [tigera/operator#2219]
CVEs found in tigera/operator v1.27.12

Our Security Scanning tools have identified CVEs in tigera/operator v1.27.12. Can you please review this and help us with an update on following:

Documentation that explains the mitigation strategy that we can apply to reduce the severity level

Details on when is this going to be fixed with the expected version number and if its already fixed which version number is it fixed in.

Issues found in build: tigera/operator v1.27.12

CVE Description 

github.com/aws/aws-sdk-go module prior to v1.33.0 is vulnerable to Password Hash With Insufficient Computational Effort. The AWS S3 Crypto SDK sends an unencrypted hash of the plaintext alongside the ciphertext as a metadata field. This hash can be used to brute force the plaintext if the hash is readable to the attacker.

**Comment by jignesh01** [comment]
Hello team,

Any update on the above issue?

**Comment by tmjd** [comment]
Same as https://github.com/tigera/operator/issues/2116#issuecomment-1297221272.
I'll add on that this has been picked to the release-v1.28 release branch so the next v1.28 release should fix this.
