### ISSUE TITLE
Change default log_file_max_size

### ISSUE THREAD

**Issue by PKizzle** [tigera/operator#2402]
## Current Behavior

As discussed in https://github.com/tigera/operator/issues/2239 it is currently not possible to adjust many of the cni configuration options described in https://projectcalico.docs.tigera.io/reference/cni-plugin/configuration when using the operator. Especially on devices with a low storage space capacity the default setting of storing up to 10 files with up to 100 MB each becomes a problem.

## Possible Solution

Allow configuration of the most needed cni configuration options such as the log file size configuration.

## Context

I currently use logrotate ontop of the internal log rotation mechanism in order to keep the log file smaller than 100 MB.

## Your Environment

* Operating System and version: Raspberry Pi OS - Debian GNU/Linux 11 (bullseye)

**Comment by ti-afra** [comment]
Please check the original ticket for the latest update on the requested feature. The newly introduced feature is addressing your concern. It would be great if you can verify that.

**Comment by PKizzle** [comment]
Looks great. I will check the added feature in detail once a new version is released. So, I will close this issue.
