### ISSUE TITLE
calico 3.21.6 deploys a windows-upgrade daemonset in 1.24.9 clusters

### ISSUE THREAD

**Issue by junjiezhang1997** [tigera/operator#2452]
When I create an aks cluster with calico for testing according to [Create an AKS cluster for Calico network policies](https://learn.microsoft.com/en-us/azure/aks/use-network-policies#create-an-aks-cluster-for-calico-network-policies), I find that calico-windows-upgrade daemonset still exists.

## Expected Behavior
calico-windows-upgrade daemonset is not deployed according to https://github.com/rancher/rke2/issues/2556.

## Current Behavior
calico-windows-upgrade daemonset is deployed.
![image](https://user-images.githubusercontent.com/109257558/216874952-8800ccca-878d-4ef3-9393-657e7200d482.png)

## Steps to Reproduce (for bugs)

1. az aks create \
    --resource-group $RESOURCE_GROUP_NAME \
    --name $CLUSTER_NAME \
    --node-count 1 \
    --windows-admin-username $WINDOWS_USERNAME \
    --network-plugin azure \
    --network-policy calico
2. az aks nodepool add \
    --resource-group $RESOURCE_GROUP_NAME \
    --cluster-name $CLUSTER_NAME \
    --os-type Windows \
    --name npwin \
    --node-count 1
3. az aks get-credentials --resource-group $RESOURCE_GROUP_NAME --name $CLUSTER_NAME
4. kubectl get daemonset -A

## Your Environment
k8s version: 1.24.9
caclico version: 3.21.6

* Operating System and version:
* Link to your project (optional):

**Comment by tmjd** [comment]
The RKE bug you linked to was fixed by only deploying the daemonset on AKS. You are using AKS so it is expected that you would have the daemonset.
What is the problem that the daemonset is causing?

**Comment by junjiezhang1997** [comment]
Not any problem observed yet. We noticed this daemonset and there is not any pod deployed on it. It seems like this daemonset is not used at all, so we are curious whether there is any bug here. Thanks for your explanation!

**Comment by tmjd** [comment]
The daemonset selects only nodes running windows, so that if any are added to the cluster and need to be upgraded they will be. I don't believe you are seeing any bug.
