### ISSUE TITLE
no longer needed replace line in go.mod

### ISSUE THREAD

**Issue by Morty-luo** [tigera/operator#2465]
It seems that `tigera/operator` at now indirectly depends on newer version `v0.5.0` of `golang.org/x/text`.
Keep according replace line in go.mod makes no sense but limits the update of `golang.org/x/text`. Should it be dropped? <br>
<https://github.com/tigera/operator/blob/master/go.mod#L107>
```txt
golang.org/x/text v0.5.0 // indirect
```
<https://github.com/tigera/operator/blob/master/go.mod#L132>
```txt
replace (
	...
	golang.org/x/text => golang.org/x/text v0.4.0
)
```

**Comment by tmjd** [comment]
This was done in the linked PR #2464 , so I'm going to close this. Thank you for pointing this out.
