### ISSUE TITLE
ImagePullpolicy Not Configurable

### ISSUE THREAD

**Issue by maxpaynebeck** [tigera/operator#2491]
## Expected Behavior
We should be able to configure imagepullpolicy via values.yml file

## Current Behavior
Currently the imagepullpolicy is hardcoded in deployment template.

## Possible Solution
We can modify/configure a template for deployment, etc to able to configure it via values file

## Steps to Reproduce (for bugs)

1. Create any deployment & it will always have the imagepullpolicy as If not present

## Context

We are unable to configure it at root, leading to argocd outofsync. I know they are other way to do but we need the solution in the official chart as we only use them.

**Comment by tmjd** [comment]
It is not expected that the operator is installed with a manifest from this repo, but I'm assuming you are probably referring to installations from the Calico project, please open this issue against the repo containing the manifest you are using. I would assume for github.com/projectcalico/calico
