### ISSUE TITLE
operator crashing looking for libdl.so.2?

### ISSUE THREAD

**Issue by paulgmiller** [tigera/operator#2492]
Calico not caching expected library

## Expected Behavior
Shouldn't crash regardless of libraries on nodes

## Current Behavior
libraries: libdl.so.2: cannot open shared object file: No such file or directory

## Possible Solution
delete this library from var lib in node hosting calic?

## Your Environment

* Operating System and version:
* Link to your project (optional):

**Comment by wedaly** [comment]
We tracked this issue down to an issue with aqua-sec (likely the same one reported here: https://github.com/zalando/postgres-operator/issues/758). This issue is unrelated to Calico.

**Comment by tmjd** [comment]
This is the operator repo, are you having this issue with tigera/operator or with calico/typha that your message seems to indicate.
If with typha I'd suggest creating an issue on github.com/projectcalico/calico
