### ISSUE TITLE
Duplicate FELIX_HEALTHPORT environment variable causing problems in Openshift

### ISSUE THREAD

**Issue by dzacball** [tigera/operator#2783]
When installing Calico with Tigera operator on Openshift, the environment variable `FELIX_HEALTHPORT` is duplicated in `calico-node` pods.

## Expected Behavior
`FELIX_HEALTHPORT` should not be duplicated in the calico-node Daemonset for Openshift clusters.

## Current Behavior
`FELIX_HEALTHPORT` is duplicated in the calico-node Daemonset or Openshift clusters.

## Possible Solution
I'm not exactly sure how this should be handled/fixed. 
Ever since the PR https://github.com/tigera/operator/pull/1955 was merged, there have been two instances of this environment variable present for `calico-node` on Openshift. 
First one is inserted here: https://github.com/tigera/operator/blob/af15d9ba47d3c4a772030ea61e9a9570ddaa81c1/pkg/render/node.go#L1388 
second one is inserted here (in case of `operatorv1.ProviderOpenShift`): https://github.com/tigera/operator/blob/af15d9ba47d3c4a772030ea61e9a9570ddaa81c1/pkg/render/node.go#L1657-L1659

## Steps to Reproduce (for bugs)
1. Install Calico on an Openshift 4.13 cluster using the Tigere Operator.

## Context
The duplication of the environment variable alone wouldn't be a huge problem. However, there is a K8s bug present in 1.26 (which Openshift 4.13 is based on) which causes the Pod Garbage Collector to fail for pods that have duplicated environment variables. This is well described in https://github.com/kubernetes/kubernetes/issues/118261.
This bug, combined with the duplicated `FELIX_HEALTHPORT` environment variable for `calico-node` will result in `calico-node` pods not being cleaned up after a k8s node is deleted, and this eventually can keep calico-node rolling update from succeeding (due to the `maxUnavailable` rollingUpdate setting).

## Your Environment
Openshift 4.13 + latest Tigera Operator

**Comment by dzacball** [comment]
I created a PR with a possible fix for this at https://github.com/tigera/operator/pull/2785.

**Comment by rene-dekker** [comment]
Thank you for raising this issue and for helping with a solution. I did some delving into the history of this repo. From what I understand:
This commit was present in 2019: https://github.com/tigera/operator/blame/eda3df71a96ec8d4aab6665feddfb41a8dc8a1c7/pkg/render/node.go#L482
At the time, this was the only reference to FELIX_HEALTHPORT in the code base. I think later refactors caused a possibility for a duplicate.

The core_controller is already setting the port for openshift. And in the current code base FELIX_HEALTHPORT is already set to the port in the configuration. Therefore, I believe  a simpler fix could solve this installation issue: https://github.com/tigera/operator/pull/2795

**Comment by dzacball** [comment]
Very nice, thanks a lot for spending time with this and providing a quick fix!
