### ISSUE TITLE
Installation CRD not getting status updated

### ISSUE THREAD

**Issue by jayunit100** [tigera/operator#2851]
xref https://github.com/projectcalico/calico/issues/7986

I *think* this might be a tigera operator issue, but am not sure, b/c maybe there's an underlying bug in the node agent that prevents it from reflecting the *spec* for GBPEnabled=False into the *status*.

# Version

quay.io/tigera/operator:v1.30.4

**Comment by tmjd** [comment]
As [commented on the bug](https://github.com/projectcalico/calico/issues/7986#issuecomment-1708517347) in the calico repo this is expected behavior since the expected calico components are not ready and healthy.
