### ISSUE TITLE
document procedure to completely uninstall calico and operator from cluster

### ISSUE THREAD

**Issue by dberardo-com** [tigera/operator#2858]
i am trying to remove calico completely from a cluster, but cannot find any official guide on how to do that.

turning all workloads down leads to an "unreachable" taint on all nodes... here a similar issue: https://github.com/projectcalico/calico/issues/7816

**Comment by tmjd** [comment]
I think the issue raised on calico is sufficient to track this request to document uninstalling calico, I'm going to close this so we don't have this duplicate request.
There is nothing this operator can do without there first being a path for Calico to be removed and have everything cleaned up.
