### ISSUE TITLE
feature request: calico-apiserver PodDisruptionBudget

### ISSUE THREAD

**Issue by dpiddock** [tigera/operator#2886]
No PodDisruptionBudget is created for the `calico-apiserver` deployment.

## Expected Behavior

PodDisruptionBudget created for `calico-apiserver`, similar to the `calico-typha` deployment.

## Current Behavior

No PDB

## Possible Solution

Generate a PodDisruptionBudget when creating the Deployment

## Steps to Reproduce (for bugs)

1. Install operator
2. `kubectl -n calico-apiserver get pdb`
3. no result

## Context

The `calico-apiserver` deployment is configured with 2 replicas. To avoid service interruption when replacing a lot of nodes at once (e.g. during version upgrade) the deployment should be configured with a PodDisruptionBudget. Similar to the `calico-typha` deployment.

## Your Environment

* Operating System and version: AWS EKS Kubernetes 1.26
* Link to your project (optional):

Thank you

**Comment by MuhtasimTanmoy** [comment]
I would like to work on this issue.

**Comment by MuhtasimTanmoy** [comment]
Requesting review for https://github.com/tigera/operator/pull/2940.

Would like to mention one issue for testing though. 

 When applying this command.
`kubectl create -f ./config/samples/operator_v1_apiserver.yaml`

It was failing to pull `calico/apiserver:master` or `calico/apiserver:latest` from docker. 
Though `calico/apiserver:master-amd64` worked in my case.

So I changed the version to `master-amd64` to make it work though it is not included in pull request. https://github.com/tigera/operator/blob/077f7483633898b43050b7cfcca9935eea34ebf0/pkg/components/calico.go#L92
