### ISSUE TITLE
Uninstallation Failure: Calico Module Leaves Remaining Jobs Blocking Deletion

### ISSUE THREAD

**Issue by rohanvivek** [tigera/operator#3159]
## Expected Behavior

The Calico module should uninstall cleanly without any errors or leftover jobs interfering with the process.

## Current Behavior

During the uninstallation process, a job named `tigera-operator-uninstall` is created, which prevents the deletion of the Calico module. This results in an error message indicating that the job already exists, halting the uninstallation process.

## Possible Solution

Manually deleting the `tigera-operator-uninstall` job via the CLI in parallel with the destruction process resolves the issue. However, a more automated solution within the Terraform module itself would be ideal.

## Steps to Reproduce (for bugs)

1. Install the Calico module using Terraform.
2. Attempt to uninstall the Calico module using Terraform.
3. Observe the creation of the `tigera-operator-uninstall` job.
4. Note the error message indicating the job already exists, preventing uninstallation.

## Context

This issue is affecting the smooth operation of the Calico module uninstallation process. I am trying to cleanly remove the Calico module from my Kubernetes cluster without encountering errors.

## Your Environment

* OS: Ubuntu 22.04.3 LTS (GitHub Runner)
* Kubernetes version: 1.29
* Tigera-operator version: v3.27.0

**Comment by tmjd** [comment]
There is not an official Calico Terraform module. I'd suggest finding the source of the module and submitting an issue there. If you do locate the source of the module, I would appreciate a link to that source.
