### ISSUE TITLE
How to deploy specific tigera operator version on OpenShift 4.x

### ISSUE THREAD

**Issue by krisiasty** [tigera/operator#640]
## Expected Behavior
Each operator release should also contain complete set of manifests required for deployment on supported platforms (like OpenShift 4.x).

## Current Behavior
Currently, documentation says that for deployment on OpenShift 4.x I should download set of files from "https://docs.projectcalico.org/manifests/...", but it is not clearly stated which version will be used or how to use different version than the one which is hardcoded in the above manifests (currently: 1.5.0).

I could try and modify image version after downloading those manifests, but then I'm not sure if some CRDs have not been changed (or added) in the release I'm interested in, or if I have to also change image version for init container (and which one should be used).

## Possible Solutions

1. provide versioned documentation page (https://docs.projectcalico.org/getting-started/openshift/installation) where each version refers to the manifests for specific release, or
2. add proper files with manifests (as zip and/or tgz archive) to each release on github and update documentation once to refer to these archives instead of specific files with hardcoded operator version.

**Comment by tmjd** [comment]
I believe we have solution 1 already. What the docs seem to be missing is a link to get get to the versioned v3.14 release, it does exist at https://docs.projectcalico.org/archive/v3.14/getting-started/openshift/installation. You can find the older versions by going to https://docs.projectcalico.org/releases and selecting the version you want. (the v3.14 link goes to the non-versioned path)

**Comment by krisiasty** [comment]
Not exactly what I'm looking for. These are calico releases, not tigera operator releases. There is no clear correlation and none of those pages even mention which version of the operator image will be used. Also, none of the versions allows to install tigera operator 1.6.x

**Comment by tmjd** [comment]
Why are you interested in installing a specific version of the operator? I would suggest not being concerned with a specific operator version but using the operator that is bundled with a specific Calico release. A Calico release includes the component versions that have been tested together and marked as a release.

**Comment by krisiasty** [comment]
I believe at the time I raised this issue there were some issues forcing us to use specific version of the operator, but that was long time ago.
