### ISSUE TITLE
Update the documentation to indicate the Use Cases supported by Calico Operator

### ISSUE THREAD

**Issue by sb1975** [tigera/operator#659]
## Expected Behavior
What use cases are supported by Calico Operator and how is that being achieved.
Some details/steps for the same would be very helpful - like upgrades of version, changing to calico enterprise ..

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@sb1975 The Calico operator use cases include managing the lifecycle of the Calico software components. 

Documentation can be found at https://docs.projectcalico.org, and within this repo.
