### ISSUE TITLE
Prometheus metrics for Typha - Currently hard coded

### ISSUE THREAD

**Issue by cyclops8456** [tigera/operator#799]
After setting up the operator and configuring Felix to supply Prometheus metrics via the FelixConfiguration CR (which is all working fine), I then went on a hunt for enabling the same for Typha.  This can be enabled if you go the non operator route and just use manifests to deploy Calico, but I'm trying to stick with operators where possible, but it currently looks like this is non-configurable via the operator as the environment variables supplied to Typha are all hard coded (unless I've completely missed something), as per the link below.

https://github.com/tigera/operator/blob/b8c354980fbd17bb81328ef633647d9711befec2/pkg/render/typha.go#L418

As Typha uses host networking, this obviously raises a possible on the security / port already in use front, and while I could just do a custom build of the operator with these hard coded to enabled and set to the appropriate port for my environment, I wanted to see if there were any plans to add a CRD for configuring Typha in the same manner as Felix?

**Comment by tmjd** [comment]
We do want to add configuration for Typha prometheus.
The two options would be:
* Add a TyphaMetricsPort to the Installation CRD (we already have NodeMetricsPort)
* I think the preference would be to add a TyphaConfiguration CR (which doesn't exist yet) and then add configuration there,  that would require a bit more work to add the new CR.

**Comment by cyclops8456** [comment]
> I think the preference would be to add a TyphaConfiguration CR

TBH, that would be my preference, as stays in keeping with CRs for operators.  At least I haven't missed anything obvious, I'll have a look at what's required and go from there.

**Comment by zeysh** [comment]
@cyclops8456 the workaround I use:

patch the calico-system/calico-typha deployment and add 
```yaml
- name: TYPHA_PROMETHEUSMETRICSENABLED
  value: "true"
- name: TYPHA_PROMETHEUSMETRICSPORT
  value: "9093"
```
to the env section for typha container.

**Comment by tmjd** [comment]
@zeysh When the operator next reconciles it would remove those (change the deployment back to what it expects), so I would expect your changes to get reverted at some point.

**Comment by tmjd** [comment]
This is available now in the Installation CR as "TyphaMetricsPort" https://docs.projectcalico.org/reference/installation/api#operator.tigera.io/v1.InstallationSpec
Please comment if this does not meet your needs and I can re-open this.
