### ISSUE TITLE
Manifest contains image tag that doesn't exist

### ISSUE THREAD

**Issue by camertron** [tigera/operator#992]
## Expected Behavior

I expect to be able to start the operator in my cluster.

## Current Behavior

I'm trying to run `kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml` and getting an image pull backoff. Inspecting the manifest, it looks like the image it's trying to use is quay.io/tigera/operator:v1.10.8. Unfortunately the "v1.10.8" tag doesn't exist in Quay, although "1.10.8" does. Did someone miss a "v" somewhere in the build process?

## Possible Solution

Tag the image correctly :)

**Comment by tmjd** [comment]
Thank you for the report. I believe this has been addressed. The image has been updated with v1.10.9 which the docs now reference.

**Comment by camertron** [comment]
Awesome, thanks @tmjd!
